alpha: 0.5
m: 0.7

gpu_num: 3 # our team's is 3
epoch: 300

num_classes: 41
split_ratio: 0.95

batch_size: 64

lr: 0.0001

save_path: ./check_points/TAST_SpecNetMFN_noisy_arcmix.pth

mode: noisy_arcmix # select one of ['arcface', 'arcmix', 'noisy_arcmix']

net_name: TAST_SpecNetMFN # select one of ['SCLTFSTgramMFN', 'TASTgramMFN', 'TFSTgramMFN', 'SpecNetMFN', 'TAST_SpecNetMFN']