hidden_dim: 256
n_layers: 6
n_heads: 16
pf_dim: 64
dropout_ratio: 0.0

alpha: 0.5
m: 0.7

gpu_num: 0
epoch: 300

num_classes: 41
split_ratio: 0.95

batch_size: 64

lr: 0.0001

save_path: ./check_points/Ablation/STSAS_NoisyArcMix_v2.pth

mode: noisy_arcmix # select one of ['arcface', 'arcmix', 'noisy_arcmix']

