alpha: 0.5
m: 0.7

gpu_num: 3 # our team's is 3
epoch: 300

num_classes: 41
split_ratio: 0.95

batch_size: 64

lr: 0.0001

temp_coeff: 0.02

mode: noisy_arcmix # select one of ['arcface', 'arcmix', 'noisy_arcmix']
net_name: TASTgramMFN_FPH # select one of ['TASTgramMFN', 'SCLTFSTgramMFN']
loss_name: cross_entropy_supcon # select one of ['cross_entropy', 'cross_entropy_supcon']

htn: 64
