alpha: 0.5
m: 0.7

gpu_num: 3 # our team's is 3
epoch: 300

num_classes: 41
split_ratio: 0.95

batch_size: 32

lr: 0.0001

save_path: ./check_points/temporal_attention_noisy_arcmix_stack.pth

mode: noisy_arcmix # select one of ['arcface', 'arcmix', 'noisy_arcmix']
net_name: TASTWgramMFN
htn: 64