alpha: 0.5
batch_size: 64
epoch: 300
gpu_num: 7
htn: 64
lbl_smth: 0.0
loss_name: cross_entropy
lr: 0.0001
m: 0.7
mode: noisy_arcmix
net_name: TAST_SpecNetMFN_nrm2
num_classes: 41
split_ratio: 0.95
temp_coeff: 0.02
